export interface GameTemplate {
  id: string;
  title: string;
  description: string;
  category: string;
  difficulty: "beginner" | "intermediate" | "advanced";
  thumbnail: string;
  prompt: string;
  tags: string[];
  estimatedTime: string;
  features: string[];
}

export const GAME_TEMPLATES: GameTemplate[] = [
  {
    id: "obby",
    title: "Classic Obby",
    description: "A challenging obstacle course with checkpoints, kill bricks, and a victory area.",
    category: "Platformer",
    difficulty: "beginner",
    thumbnail: "/templates/obby.svg",
    prompt: "Create a 20-stage obby with checkpoints at every 5 stages, kill bricks, moving platforms, spinner obstacles, and a victory room with fireworks at the end. Include a stage counter GUI and a skip stage button.",
    tags: ["obby", "platformer", "checkpoints"],
    estimatedTime: "2 min",
    features: ["20 stages", "Checkpoints", "Kill bricks", "Moving platforms", "Victory room"],
  },
  {
    id: "tycoon",
    title: "Tycoon Base",
    description: "A fully functional tycoon with droppers, upgraders, conveyors, and a shop.",
    category: "Tycoon",
    difficulty: "intermediate",
    thumbnail: "/templates/tycoon.svg",
    prompt: "Build a tycoon game with a dropper that spawns parts onto a conveyor belt leading to a collector. Add upgraders that increase part value, a shop GUI to buy new droppers and upgraders, and a rebirth system that resets everything but gives a permanent multiplier.",
    tags: ["tycoon", "economy", "dropper"],
    estimatedTime: "5 min",
    features: ["Droppers", "Conveyors", "Upgraders", "Shop GUI", "Rebirth system"],
  },
  {
    id: "sword-fight",
    title: "Sword Fighting Arena",
    description: "PvP combat arena with sword mechanics, combos, and a leaderboard.",
    category: "Combat",
    difficulty: "intermediate",
    thumbnail: "/templates/combat.svg",
    prompt: "Create a sword fighting game with a 3-hit combo system, blocking, a dash ability, and special attacks. Add a round-based system with a lobby, kill/death leaderboard, and weapon skins unlockable with coins earned from kills.",
    tags: ["combat", "pvp", "swords"],
    estimatedTime: "5 min",
    features: ["Combo system", "Blocking", "Dash", "Round system", "Leaderboard"],
  },
  {
    id: "simulator",
    title: "Pet Simulator",
    description: "Collect pets, level them up, trade with others, and explore zones.",
    category: "Simulator",
    difficulty: "advanced",
    thumbnail: "/templates/simulator.svg",
    prompt: "Build a pet simulator with egg hatching (common, rare, legendary, mythic rarities), pet leveling, an inventory system, pet trading between players, multiple biome zones that unlock with coins, and auto-farming pets that collect coins for you.",
    tags: ["simulator", "pets", "trading"],
    estimatedTime: "8 min",
    features: ["Egg hatching", "Pet leveling", "Trading", "Multiple zones", "Auto-farm"],
  },
  {
    id: "horror",
    title: "Horror Escape",
    description: "A scary escape room with puzzles, a monster AI, and atmospheric lighting.",
    category: "Horror",
    difficulty: "advanced",
    thumbnail: "/templates/horror.svg",
    prompt: "Create a horror escape game with dark atmospheric lighting, a monster NPC that patrols and chases players on sight, key and lock puzzles, hiding spots, a flashlight with limited battery, and 3 escape rooms of increasing difficulty.",
    tags: ["horror", "escape", "puzzle"],
    estimatedTime: "6 min",
    features: ["Monster AI", "Puzzles", "Flashlight", "Hiding spots", "3 rooms"],
  },
  {
    id: "racing",
    title: "Racing Circuit",
    description: "Vehicle racing with boost pads, laps, and a finish-line leaderboard.",
    category: "Racing",
    difficulty: "intermediate",
    thumbnail: "/templates/racing.svg",
    prompt: "Build a racing game with a VehicleSeat car system, a looping track with boost pads and ramps, lap counting, a race timer, position tracking, and a finish-line leaderboard. Add a car customization menu with paint colors.",
    tags: ["racing", "vehicles", "speed"],
    estimatedTime: "5 min",
    features: ["Vehicle physics", "Boost pads", "Lap system", "Leaderboard", "Car colors"],
  },
  {
    id: "roleplay",
    title: "Roleplay Town",
    description: "An open-world roleplay map with jobs, houses, vehicles, and an economy.",
    category: "Roleplay",
    difficulty: "advanced",
    thumbnail: "/templates/roleplay.svg",
    prompt: "Create a roleplay game with a town map containing houses players can own, job locations (police, firefighter, chef, doctor), a vehicle spawn system, a currency system with ATMs, a phone GUI for communication, and a day/night cycle.",
    tags: ["roleplay", "town", "jobs"],
    estimatedTime: "10 min",
    features: ["Housing", "Jobs system", "Vehicles", "Economy", "Day/night cycle"],
  },
  {
    id: "tower-defense",
    title: "Tower Defense",
    description: "Place towers to defend against waves of enemies on a path.",
    category: "Strategy",
    difficulty: "advanced",
    thumbnail: "/templates/td.svg",
    prompt: "Build a tower defense game with a winding path for enemies, tower placement on a grid, multiple tower types (archer, mage, cannon, sniper) with upgrade levels, wave-based enemy spawning with increasing difficulty, and a lives/health system.",
    tags: ["tower-defense", "strategy", "waves"],
    estimatedTime: "8 min",
    features: ["Tower placement", "4 tower types", "Upgrades", "Wave system", "Boss waves"],
  },
  {
    id: "murder-mystery",
    title: "Murder Mystery",
    description: "One murderer, one sheriff, rest are innocents. Classic whodunit.",
    category: "Social",
    difficulty: "intermediate",
    thumbnail: "/templates/mystery.svg",
    prompt: "Create a murder mystery game with role assignment (murderer gets a knife, sheriff gets a gun, rest are innocents), a map with hiding spots and corridors, coin collection for innocents, round timer, and a lobby with a player count requirement to start.",
    tags: ["murder-mystery", "social", "rounds"],
    estimatedTime: "5 min",
    features: ["Role system", "Knife/Gun", "Rounds", "Lobby", "Coin collection"],
  },
  {
    id: "battlegrounds",
    title: "Anime Battlegrounds",
    description: "Ability-based combat with unique characters and ultimate moves.",
    category: "Combat",
    difficulty: "advanced",
    thumbnail: "/templates/battlegrounds.svg",
    prompt: "Build an anime-style battlegrounds game with 4 playable characters, each with 4 abilities (M1 combo, ability 1, ability 2, ultimate). Add a health/mana system, ability cooldowns, hit effects with screen shake, a character select screen, and 1v1/FFA modes.",
    tags: ["anime", "battlegrounds", "abilities"],
    estimatedTime: "10 min",
    features: ["4 characters", "Ability system", "Ultimates", "1v1 mode", "FFA mode"],
  },
  {
    id: "survival",
    title: "Survival Island",
    description: "Gather resources, craft tools, build a shelter, and survive the night.",
    category: "Survival",
    difficulty: "advanced",
    thumbnail: "/templates/survival.svg",
    prompt: "Create a survival game on an island with resource gathering (wood, stone, food), a crafting system with recipes, a hunger/thirst/health system, shelter building with placeable walls and roofs, hostile mobs that spawn at night, and a campfire for warmth.",
    tags: ["survival", "crafting", "building"],
    estimatedTime: "10 min",
    features: ["Resource gathering", "Crafting", "Building", "Hunger system", "Night mobs"],
  },
  {
    id: "showcase",
    title: "Game Showcase",
    description: "A beautiful showcase map with terrain, lighting, and atmosphere.",
    category: "Showcase",
    difficulty: "beginner",
    thumbnail: "/templates/showcase.svg",
    prompt: "Create a stunning showcase with smooth terrain (mountains, valleys, a lake), realistic lighting with Atmosphere, Bloom, and ColorCorrection, trees and grass using MeshParts, a walking path with benches, and ambient bird sounds.",
    tags: ["showcase", "terrain", "lighting"],
    estimatedTime: "3 min",
    features: ["Terrain sculpting", "Realistic lighting", "Atmosphere", "Nature props", "Ambient audio"],
  },
];

export const TEMPLATE_CATEGORIES = [
  "All",
  "Platformer",
  "Tycoon",
  "Combat",
  "Simulator",
  "Horror",
  "Racing",
  "Roleplay",
  "Strategy",
  "Social",
  "Survival",
  "Showcase",
];
